import {
  Utensils,
  ChefHat,
  Soup,
  Salad,
  Fish,
  Beef,
  Drumstick,
  Ham,
  Egg,
  EggFried,
  Pizza,
  Sandwich,
  Hamburger,
  IceCream,
  IceCreamCone,
  Cake,
  CakeSlice,
  Cupcake,
  Cookie,
  Croissant,
  Donut,
  Popcorn,
  Wheat,
  Carrot,
  Apple,
  Banana,
  Cherry,
  Grape,
  Citrus,
  Milk,
  Coffee,
  Wine,
  Beer,
  Candy,
  Vegan,
  LeafyGreen,
  Nut,
  type LucideIcon,
} from 'lucide-react';

// Feste Auswahl an Rezept-Icons (ersetzt die frühere bunte Emoji-Auswahl).
export const RECIPE_ICONS = [
  'utensils',
  'chef-hat',
  'soup',
  'salad',
  'fish',
  'beef',
  'drumstick',
  'ham',
  'egg',
  'egg-fried',
  'pizza',
  'sandwich',
  'hamburger',
  'ice-cream',
  'ice-cream-cone',
  'cake',
  'cake-slice',
  'cupcake',
  'cookie',
  'croissant',
  'donut',
  'popcorn',
  'wheat',
  'carrot',
  'apple',
  'banana',
  'cherry',
  'grape',
  'citrus',
  'milk',
  'coffee',
  'wine',
  'beer',
  'candy',
  'vegan',
  'leafy-green',
  'nut',
] as const;

export type RecipeIconKey = (typeof RECIPE_ICONS)[number];

const ICON_COMPONENTS: Record<RecipeIconKey, LucideIcon> = {
  utensils: Utensils,
  'chef-hat': ChefHat,
  soup: Soup,
  salad: Salad,
  fish: Fish,
  beef: Beef,
  drumstick: Drumstick,
  ham: Ham,
  egg: Egg,
  'egg-fried': EggFried,
  pizza: Pizza,
  sandwich: Sandwich,
  hamburger: Hamburger,
  'ice-cream': IceCream,
  'ice-cream-cone': IceCreamCone,
  cake: Cake,
  'cake-slice': CakeSlice,
  cupcake: Cupcake,
  cookie: Cookie,
  croissant: Croissant,
  donut: Donut,
  popcorn: Popcorn,
  wheat: Wheat,
  carrot: Carrot,
  apple: Apple,
  banana: Banana,
  cherry: Cherry,
  grape: Grape,
  citrus: Citrus,
  milk: Milk,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  candy: Candy,
  vegan: Vegan,
  'leafy-green': LeafyGreen,
  nut: Nut,
};

// Bereits gespeicherte, alte Emojis auf ein passendes Icon abbilden, damit
// bestehende Rezepte ohne Datenbank-Migration trotzdem ein sinnvolles Icon zeigen.
const LEGACY_EMOJI_TO_ICON: Record<string, RecipeIconKey> = {
  '🥣': 'soup',
  '🥗': 'salad',
  '🐟': 'fish',
  '🥩': 'beef',
  '🍳': 'egg-fried',
  '🥞': 'cake-slice',
  '🍜': 'soup',
  '🍝': 'wheat',
  '🥘': 'soup',
  '🫕': 'soup',
  '🥧': 'cake-slice',
  '🍰': 'cake-slice',
  '🎂': 'cake',
  '🍩': 'donut',
  '🍪': 'cookie',
  '🥐': 'croissant',
  '🥨': 'croissant',
  '🧀': 'milk',
  '🥚': 'egg',
  '🧆': 'vegan',
  '🌮': 'sandwich',
  '🌯': 'sandwich',
  '🥙': 'sandwich',
  '🧇': 'cake-slice',
  '🥓': 'ham',
  '🥪': 'sandwich',
  '🍱': 'utensils',
  '🍛': 'soup',
  '🍲': 'soup',
  '🫔': 'sandwich',
  '🥦': 'leafy-green',
  '🥕': 'carrot',
  '🥑': 'leafy-green',
  '🍋': 'citrus',
  '🍓': 'cherry',
  '🫐': 'grape',
  '🍇': 'grape',
  '🍒': 'cherry',
  '🍑': 'apple',
  '🫙': 'utensils',
  '🍽️': 'utensils',
  '🥄': 'utensils',
  '🍴': 'utensils',
  '🧂': 'utensils',
  '🫚': 'carrot',
  '🥜': 'nut',
  '🌾': 'wheat',
  '🥬': 'leafy-green',
  '🍅': 'salad',
  '🧅': 'carrot',
};

const DEFAULT_ICON: RecipeIconKey = 'utensils';

export function isRecipeIconKey(value: string): value is RecipeIconKey {
  return Object.prototype.hasOwnProperty.call(ICON_COMPONENTS, value);
}

/**
 * Löst einen gespeicherten Wert (neuer Icon-Key oder ein altes, direkt in der
 * Datenbank stehendes Emoji) in eine Lucide-Icon-Komponente auf.
 */
export function getRecipeIcon(value: string): LucideIcon {
  if (isRecipeIconKey(value)) return ICON_COMPONENTS[value];
  const mapped = LEGACY_EMOJI_TO_ICON[value];
  return ICON_COMPONENTS[mapped ?? DEFAULT_ICON];
}
